services:
  app:
    image: node:20
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - PNPM_HOME=/pnpm
      - PATH=$PNPM_HOME:$PATH
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - pnpm-store:/pnpm/store
    command: |
      sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm start"
  postgres:
    image: postgis/postgis:17-3.5-alpine
    environment:
      POSTGRES_USER: resin
      POSTGRES_PASSWORD: development
      POSTGRES_DB: resin
    ports:
      - '5432:5432'
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
  typesense:
    image: typesense/typesense:27.1
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: resin_development
      TYPESENSE_ENABLE_CORS: '${TYPESENSE_ENABLE_CORS:-true}'
    volumes:
      - typesense:/data
    ports:
      - 8109:8108

volumes:
  node_modules:
  pnpm-store:
  typesense:
